'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const page=location.pathname.split('/').pop()||'index.html';
$$('.nav-links a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')});
const menu=$('.menu-btn'),nav=$('.nav-links');if(menu){menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
const words=['Cloud Engineer','DevOps Engineer','AWS & Azure Practitioner','DevSecOps Practitioner'];let wi=0,ci=0,deleting=false;const typed=$('.typed');function type(){if(!typed)return;const w=words[wi];typed.textContent=w.slice(0,ci);if(!deleting&&ci<w.length)ci++;else if(deleting&&ci>0)ci--;else{deleting=!deleting;if(!deleting)wi=(wi+1)%words.length}setTimeout(type,deleting?45:ci===w.length?1200:75)}type();
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e));
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$$('[data-category]').forEach(c=>c.hidden=f!=='all'&&!c.dataset.category.includes(f))}));
const search=$('#skillSearch');if(search)search.addEventListener('input',()=>{$$('.skill').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(search.value.toLowerCase()))});
const form=$('#contactForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent(data.get('subject')||'Portfolio enquiry');const body=encodeURIComponent(`${data.get('message')}\n\nFrom: ${data.get('name')} (${data.get('email')})`);location.href=`mailto:ambatimokeshreddy@gmail.com?subject=${subject}&body=${body}`;toast('Opening your email app…')});
function toast(msg){const t=$('.toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('Email copied') }));
const year=$('#year');if(year)year.textContent=new Date().getFullYear();
const ab=$('.assistant-btn'),panel=$('.assistant'),close=$('.assistant-close'),body=$('.assistant-body');if(ab)ab.addEventListener('click',()=>{panel.classList.toggle('open');ab.setAttribute('aria-expanded',panel.classList.contains('open'))});if(close)close.addEventListener('click',()=>panel.classList.remove('open'));
const answers={about:'Mokesh is a BCA graduate and entry-level Cloud & DevOps Engineer with hands-on AWS, Azure, Terraform, Kubernetes, CI/CD, security, and monitoring projects.',aws:'His AWS work includes a three-VPC, two-AZ highly available architecture and an 11-stage DevSecOps pipeline deployed to Amazon EKS.',azure:'His Azure work includes a secured Hub-Spoke network and automated deployment of a Flask application using GitHub Actions.',pipeline:'The 11-stage Jenkins pipeline covers checkout, dependencies, validation, SonarQube, Trivy scans, Docker build/push, EKS deployment, and observability.',contact:'You can contact Mokesh at ambatimokeshreddy@gmail.com or +91 7032183762.'};$$('.chip').forEach(c=>c.addEventListener('click',()=>{const d=document.createElement('div');d.className='bubble';d.textContent=answers[c.dataset.q];body.appendChild(d);body.scrollTop=body.scrollHeight}));
